# Generated by Django 3.2.16 on 2022-10-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticapp', '0002_place_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=250)),
                ('image1', models.ImageField(upload_to='pictures')),
                ('desc1', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='place',
        ),
    ]
